version: '3.8'
services:
    postgres:
        image: postgres:15.2
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5555:5432'
        volumes:
            - postgres-next:/var/lib/postgresql/data

volumes:
    postgres-next: