version: '3.8'
services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
      - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
      - BASE_REGISTRY_ENDPOINT=${BASE_REGISTRY_ENDPOINT}
      - REGISTRY_AUTH_TOKEN=${REGISTRY_AUTH_TOKEN}
      - LISERK_API_ENDPOINT=${LISERK_API_ENDPOINT}
      - LISERK_API_KEY=${LISERK_API_KEY}
      - GATEWAY_URL_ACCESS=${GATEWAY_URL_ACCESS}
      - LIMIT_CREATION_LAMBDA_NUM=${LIMIT_CREATION_LAMBDA_NUM}
      - NEXT_PUBLIC_GATEWAY_URL_ACCESS=${NEXT_PUBLIC_GATEWAY_URL_ACCESS}
      - NEXT_PUBLIC_BASE_REGISTRY_ENDPOINT=${NEXT_PUBLIC_BASE_REGISTRY_ENDPOINT}
      - NEXT_PUBLIC_BASE_CONTAINER_DOMAIN=${NEXT_PUBLIC_BASE_CONTAINER_DOMAIN}
      - NEXT_PUBLIC_DOCKER_HUB_URL=${NEXT_PUBLIC_DOCKER_HUB_URL}
      - NODE_ENV=development
      - NEXT_PUBLIC_PRIVATE_REGISTRY_URL=${NEXT_PUBLIC_PRIVATE_REGISTRY_URL}
      - DOCKER_HUB_REGISTRY_USERNAME=${DOCKER_HUB_REGISTRY_USERNAME}
      - DOCKER_HUB_REGISTRY_PASSWORD=${DOCKER_HUB_REGISTRY_PASSWORD}
      - CRYPTO_ALGO=${CRYPTO_ALGO}
      - CRYPTO_SECRET=${CRYPTO_SECRET}