name: Stuga Cloud Web App - CI/CD

on:
    push:
        branches:
            - "*"

jobs:
    build:
        name: Install Dependencies and Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"

            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm test

            - name: Build
              run: npm run build

            - name: Log in to Docker registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ secrets.DOCKER_REGISTRY }}
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}
